---
# Source: rco-apps/charts/api-rco-2/templates/api-rco.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-rco-2-svc
  namespace: test
spec:
  selector:
    app: api-rco-2
  ports:
  - port: 80
    targetPort: 80
---
# Source: rco-apps/charts/api-rco/templates/api-rco.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-rco-svc
  namespace: test
spec:
  selector:
    app: api-rco
  ports:
  - port: 80
    targetPort: 80
---
# Source: rco-apps/charts/api-rco-2/templates/api-rco.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rco-2
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rco-2
  template:
    metadata:
      labels:
        app: api-rco-2
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: api-rco-2
        image: ghcr.io/rosecroixdor/api-rco-2:latest
        ports:
        - containerPort: 80
---
# Source: rco-apps/charts/api-rco/templates/api-rco.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-rco
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-rco
  template:
    metadata:
      labels:
        app: api-rco
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: api-rco
        image: ghcr.io/rosecroixdor/api-rco:latest
        ports:
        - containerPort: 80
---
# Source: rco-apps/charts/api-rco-2/templates/api-rco.yaml
#http redirect
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-rco-2-http-redirect
  namespace: test
spec:
  parentRefs:
  - name: http-gw
    namespace: gateway
  hostnames:
  - yeaah.lrfrance.fr
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
# Source: rco-apps/charts/api-rco-2/templates/api-rco.yaml
#httproute
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-rco-2-httproute
  namespace: test
spec:
  parentRefs:
  - name: https-gw
    namespace: gateway
  hostnames:
  - yeaah.lrfrance.fr
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: api-rco-2-svc
      port: 80
---
# Source: rco-apps/charts/api-rco/templates/api-rco.yaml
#http redirect
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-rco-http-redirect
  namespace: test
spec:
  parentRefs:
  - name: http-gw
    namespace: gateway
  hostnames:
  - test.lrfrance.fr
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
# Source: rco-apps/charts/api-rco/templates/api-rco.yaml
#httproute
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api-rco-httproute
  namespace: test
spec:
  parentRefs:
  - name: https-gw
    namespace: gateway
  hostnames:
  - test.lrfrance.fr
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: api-rco-svc
      port: 80
---
# Source: rco-apps/templates/reference-grant.yaml
#reference Grant:
kind: ReferenceGrant
apiVersion: gateway.networking.k8s.io/v1beta1
metadata:
  name: allow-gateway-from-default
  namespace: test
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: test
  to:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: http
    namespace: gateway
---
# Source: rco-apps/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  name: test
  labels:
    gateway-access: true
