apiVersion: v1
kind: Namespace
metadata:
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  name: {{ .Release.Namespace }}
  labels:
    gateway-access: true