api-rco:
  image:
    name: api-rco
    tag: latest
  http:
    redirectToHttps: false
  containerPort: 5000
  environement: test
  configMaps:
   - name: api-rco-config
     mountPath: /app
     data:
      Cors:
        AllowedOrigins:
          - http://localhost:3000
          - http://localhost:5173
    

