apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.image.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.image.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.image.name }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      containers:
      - name: {{ .Values.image.name }}
        image: {{ .Values.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:{{ .Values.image.containerPort | default 80 }}"
        - name: DOTNET_RUNNING_IN_CONTAINER
          value: "true"
        - name: DOTNET_SYSTEM_GLOBALIZATION_INVARIANT
          value: "true"
        - name: DOTNET_USE_POLLING_FILE_WATCHER
          value: "true"
        - name: DOTNET_ENVIRONMENT
          value: "{{ .Values.image.environement }}"
        {{- if .Values.configMaps }}
        volumeMounts:
        {{- range .Values.configMaps }}
        - name: {{ .name }}
          mountPath: {{ .mountPath }}/{{ .filename | default (printf "appsettings.%s.yaml" $.Values.image.environement) }}
          subPath: {{ .filename | default (printf "appsettings.%s.yaml" $.Values.image.environement) }}
          readOnly: true
        {{- end }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.image.containerPort | default 80 }}
      {{- if .Values.configMaps }}
      volumes:
      {{- range .Values.configMaps }}
      - name: {{ .name }}
        configMap:
          name: {{ .name }}
      {{- end }}
      {{- end }}
---
{{- range .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
data:
  {{ .filename | default (printf "appsettings.%s.yaml" $.Values.image.environement) }}: |
    {{- toYaml .data | nindent 4 }}
---
{{- end }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.image.name }}-svc
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.image.name }}
  ports:
  - port: 80
    targetPort: {{ .Values.image.containerPort | default 80 }}
 
---
{{- if .Values.http }}
{{- if .Values.http.redirectToHttps | default true }}
#http redirect
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.image.name }}-http-redirect
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: http-gw
    namespace: gateway
  hostnames:
  - {{ .Values.http.host | default (printf "%s.%s" .Values.image.environement (index .Values "service-endpoint-domain")) }}
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
{{- end }}
---
#httproute
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Values.image.name }}-httproute
  namespace: {{ .Release.Namespace }}
spec:
  parentRefs:
  - name: https-gw
    namespace: gateway
  hostnames:
  - {{ .Values.http.host | default (printf "%s.%s" .Values.image.environement (index .Values "service-endpoint-domain")) }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ .Values.image.name }}-svc
      port: 80
{{- end }}