on:
  workflow_call:
    inputs:
      version:
        description: 'Version to commit'
        required: true
        type: string
      image:
        description: 'Image to commit'
        required: true
        type: string
jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Commit version and image
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          #git add appsettings.yaml
          git commit -m "Update version to ${{ github.event.inputs.version }} and image to ${{ github.event.inputs.image }}"
          git push